# Generated by Django 5.1.1 on 2024-10-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('storePostal_code', models.CharField(max_length=10)),
                ('storeStreet_address', models.CharField(max_length=30)),
                ('storeJibun_address', models.CharField(blank=True, max_length=30, null=True)),
                ('storeDetail_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SigongSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinting', models.BooleanField(default=False, verbose_name='썬팅')),
                ('wrapping', models.BooleanField(default=False, verbose_name='랩핑')),
                ('ppf', models.BooleanField(default=False, verbose_name='PPF/차량보호필름')),
                ('carwash', models.BooleanField(default=False, verbose_name='세차')),
                ('gloss', models.BooleanField(default=False, verbose_name='광택')),
                ('detail_carwash', models.BooleanField(default=False, verbose_name='디테일세차')),
                ('car_repair', models.BooleanField(default=False, verbose_name='차량수리')),
                ('painting', models.BooleanField(default=False, verbose_name='판금/도장')),
                ('autoglass', models.BooleanField(default=False, verbose_name='유리교체')),
                ('tire', models.BooleanField(default=False, verbose_name='타이어')),
                ('engine_oil', models.BooleanField(default=False, verbose_name='엔진오일')),
                ('blackbox', models.BooleanField(default=False, verbose_name='블랙박스')),
                ('navigation', models.BooleanField(default=False, verbose_name='네비게이션')),
                ('led', models.BooleanField(default=False, verbose_name='LED')),
                ('rear_camera', models.BooleanField(default=False, verbose_name='후방카메라')),
                ('rear_sensor', models.BooleanField(default=False, verbose_name='후방감지기')),
                ('light_restoration', models.BooleanField(default=False, verbose_name='라이트복원')),
                ('rent_car', models.BooleanField(default=False, verbose_name='렌트카')),
            ],
        ),
        migrations.CreateModel(
            name='CarStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=20, verbose_name='가게이름')),
                ('thumbnail', models.ImageField(upload_to='car_store_thumbnail')),
                ('storeLocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carStore.location', verbose_name='가게위치')),
                ('sigongSkill', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='carStore.sigongskill', verbose_name='시공기술')),
            ],
        ),
        migrations.CreateModel(
            name='StorePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='store_photo', verbose_name='가게사진')),
                ('car_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='carStore.carstore')),
            ],
        ),
    ]
