# Generated by Django 5.1.1 on 2024-10-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstore',
            name='business_hours',
            field=models.CharField(max_length=100, null=True, verbose_name='운영시간'),
        ),
        migrations.AddField(
            model_name='carstore',
            name='holidays',
            field=models.CharField(max_length=50, null=True, verbose_name='휴무일'),
        ),
        migrations.AddField(
            model_name='carstore',
            name='store_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='가게 전화번호'),
        ),
    ]
