# Generated by Django 5.1.1 on 2024-10-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sigongSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='isShop',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CarStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=20, verbose_name='가게이름')),
                ('storeLocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.location', verbose_name='가게위치')),
                ('sigongSkill', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.sigongskill', verbose_name='시공기술')),
            ],
        ),
    ]
