# Generated by Django 5.1.1 on 2024-10-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_isshop_user_isstore_user_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isStore',
            new_name='is_Store',
        ),
    ]
