# Generated by Django 5.1.1 on 2024-10-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_isstore_user_is_store'),
        ('carStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carstore',
            name='sigongSkill',
        ),
        migrations.RemoveField(
            model_name='carstore',
            name='storeLocation',
        ),
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carStore.carstore'),
        ),
        migrations.AlterField(
            model_name='user',
            name='carModel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='detail_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='jibun_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_address',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='sigongSkill',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='CarStore',
        ),
    ]
