# Generated by Django 5.1.1 on 2024-10-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_carstore_sigongskill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='carModel',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_Store',
            new_name='is_store',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
